# Generated by Django 4.1.7 on 2023-03-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-date', 'hour')},
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(choices=[('O', 'Passengers'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default='O'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('O', 'Payment Method'), ('Cash', 'Cash'), ('Zelle', 'Zelle')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='referrals_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.referral'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_of_service',
            field=models.CharField(choices=[('O', 'Type of Service'), ('Hourly', 'Hourly'), ('One way', 'One way')], default='O', max_length=20),
        ),
    ]
