# Generated by Django 4.1.7 on 2023-02-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(choices=[('O', 'Passengers'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('O', 'Payment Method'), ('Cash', 'Cash'), ('Zelle', 'Zelle')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_of_service',
            field=models.CharField(choices=[('O', 'Type of Service'), ('Hourly', 'Hourly'), ('One way', 'One way')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
