# Generated by Django 4.1.7 on 2023-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='stars',
        ),
        migrations.AlterField(
            model_name='referral',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
