# Generated by Django 4.1.7 on 2023-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_options_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
