# Generated by Django 4.1.7 on 2023-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referrals_code',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
    ]
