# Generated by Django 4.1.7 on 2023-03-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_referral_bookings_count_referral_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hour',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(choices=[('O', 'Passengers'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('O', 'Payment Method'), ('Cash', 'Cash'), ('Zelle', 'Zelle')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='referrals_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.referral'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_of_service',
            field=models.CharField(choices=[('O', 'Type of Service'), ('Hourly', 'Hourly'), ('One way', 'One way')], default=None, max_length=20),
        ),
    ]
