# Generated by Django 4.1.7 on 2023-03-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_referral_bookings_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookings_amount',
            new_name='amount',
        ),
    ]
