# Generated by Django 4.1.7 on 2023-03-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_referral_bookings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referrals_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.referral'),
        ),
    ]
