# Generated by Django 4.1.7 on 2023-03-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_booking_referrals_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referrals_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.referral'),
        ),
    ]
