# Generated by Django 4.1.7 on 2023-03-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_booking_referrals_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrals_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
