# Generated by Django 4.1.7 on 2023-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_referral_referrals_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
